name: Phar
on:
  workflow_dispatch: {} 
  
jobs:
  build:
    name: Phar php
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.26.0
            
