name: Phar
on:
  workflow_dispatch: {} 
  
jobs:
  build:
    name: Phar php
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.26.0

    - name: Setup Phar composer
      run: curl -JOL https://clue.engineering/phar-composer-latest.phar
            
